main:
  - name: News
    url: post
    weight: 20
  - name: Toolset
    url: project
    weight: 30
  - name: Trainings
    url: event
    weight: 40
  - name: Courses
    url: course
    weight: 50
  - name: Contact
    url: contact
    weight: 60
